/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest */

#ifndef _Included_JniTest
#define _Included_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JniTest_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JniTest
 * Method:    modifybytes
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_JniTest_modifybytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
